version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: symfony
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
